import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {session ?
          <>
            Signed in as {session.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
          :
          <>
            Not signed in <br />
            <button onClick={() => signIn()}>Sign in</button>
          </>

        }
      </main>
    </div>
  )
}
